Repository GyeongNam/Alioth-Front, pull requests merged in 2024-04, with the labels that each got.

#5 Jh/fc mfrontend
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/main.js
  src/pages/board/SuggestionBoardDetailPage.vue
  vite.config.mjs
Labels: enhancement

#6 [feat] FCM 프론트 개발
  .env
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/main.js
Labels: good first issue

#8 Jh/login page01
  .env
  package-lock.json
  package.json
  src/assets/2024-03-18_2.22.312.png
  src/pages/login/LoginPage.vue
Labels: documentation

#9 Hhj/app sidebar pinia1
  package-lock.json
  package.json
  src/App.vue
  src/layouts/AppHeader.vue
  src/layouts/AppSidebar.vue
  src/pages/board/BoardAddPage.vue
  src/pages/board/BoardDetailPage.vue
  src/pages/board/BoardListPage.vue
  src/pages/board/BoardModifyPage.vue
  src/pages/board/SuggestionBoardAddPage.vue
  src/pages/board/SuggestionBoardDetailPage.vue
  src/pages/board/SuggestionBoardModifyPage.vue
  src/pages/contract/ContractAddModifyPage.vue
  src/pages/contract/ContractCancelPage.vue
  src/pages/contract/ContractDetailPage.vue
  src/pages/contract/ContractListPage.vue
  src/pages/main/HomePage.vue
  src/pages/mypage/MyPage.vue
  src/pages/sales/SalesPage.vue
  src/pages/sales/SalesPersonal.vue
  src/pages/sales/SalesRanking.vue
  src/pages/sales/SalesTeam.vue
  src/pages/sales/SalesTotal.vue
  src/pages/salesMember/SalesMembersAddPage.vue
  src/pages/salesMember/SalesMembersDetailPage.vue
  src/pages/salesMember/SalesMembersListPage.vue
  src/pages/salesMember/SalesMembersModifyPage.vue
  src/pages/schedule/SchedulePage.vue
  src/router/routes.js
  src/stores/app.js
  src/stores/dropDown.js
Labels: ⏫프론트-개발, ✅테스트

#11 Jh/contract page
  .env
  public/firebase-messaging-sw.js
  src/main.js
  src/pages/login/LoginPage.vue
  src/pages/login/PasswordFind.vue
  src/router/routes.js
Labels: ⏫프론트-개발

#12 [fix]: AppHeader에 페이지 명 로딩, 알람 아이콘, 시간 수정
  src/layouts/AppHeader.vue
  src/layouts/AppSidebar.vue
  src/pages/mypage/MyPage.vue
  src/router/routes.js
Labels: ⏫프론트-개발, 🍀코드리뷰

#13 JWT 만료시 토큰 재발급이후 재요청
  src/pages/board/BoardListPage.vue
  src/plugins/loginaxios.js
Labels: ⏫프론트-개발, 🍀코드리뷰

#14 [feat]: List Component 생성 : 계약목록 조회 적용
  src/layouts/ListComponent.vue
  src/pages/contract/ContractListPage.vue
Labels: ⏫프론트-개발, 🍀코드리뷰

#15 sidebar 로그아웃버튼 추가, contract CRUD, board CRUD 프론트 개발
  package-lock.json
  package.json
  src/layouts/AppSidebar.vue
  src/layouts/ListComponent.vue
  src/pages/board/BoardAddPage.vue
  src/pages/board/BoardDetailPage.vue
  src/pages/board/BoardListPage.vue
  src/pages/board/BoardModifyPage.vue
  src/pages/board/SuggestionBoardAddPage.vue
  src/pages/contract/ContractAddModifyPage.vue
  src/pages/contract/ContractCancelPage.vue
  src/pages/contract/ContractDetailPage.vue
  src/pages/contract/ContractListPage.vue
  src/pages/contract/ContractModifyPage.vue
  src/router/routes.js
Labels: ⏫프론트-개발, 🍀코드리뷰

#18 Jgn/schedule
  package-lock.json
  package.json
  src/layouts/AppHeader.vue
  src/pages/schedule/SchedulePage.vue
Labels: ⏫프론트-개발

#17 Jh/alarm pinia
  package-lock.json
  src/layouts/AppHeader.vue
  src/main.js
  src/pages/board/SuggestionBoardAddPage.vue
  src/stores/notificationStore.js
Labels: ⏫프론트-개발, 🍀코드리뷰

#19 [fix] 로그인시 사원 권한을 pinia에 적용
  src/pages/login/LoginPage.vue
  src/stores/loginInfo.js
Labels: ⏫프론트-개발

#20 JGN/Pr-error1
  package-lock.json
  src/layouts/AppHeader.vue
  src/layouts/AppSidebar.vue
  src/plugins/index.js
Labels: ⏫프론트-개발

#23 Jgn/schedule2
  src/layouts/AppSidebar.vue
  src/pages/login/LoginPage.vue
  src/pages/schedule/SchedulePage.vue
  src/plugins/index.js
Labels: ⏫프론트-개발

#24 Jh/code refactoring
  src/main.js
  src/pages/board/BoardAddPage.vue
  src/pages/board/BoardDetailPage.vue
  src/pages/board/BoardListPage.vue
  src/pages/board/BoardModifyPage.vue
  src/pages/board/SuggestionBoardAddPage.vue
  src/pages/contract/ContractAddModifyPage.vue
  src/pages/contract/ContractCancelPage.vue
  src/pages/contract/ContractDetailPage.vue
  src/pages/contract/ContractListPage.vue
  src/pages/contract/ContractModifyPage.vue
  src/stores/notificationStore.js
Labels: ⏫프론트-개발, 🍀코드리뷰

#25 [feat] 사원 매출 메인화면, 개인
  package-lock.json
  package.json
  src/pages/sales/SalesPage.vue
  src/pages/sales/SalesPersonal.vue
  src/pages/sales/charts/SalesPageCountPieChart.js
  src/pages/sales/charts/SalesPagePieChart.js
  src/pages/sales/charts/SalesPersonalTableChart.js
Labels: ⏫프론트-개발

#26 로그인시 상태관리에 사원의 팀코드 추가
  src/pages/login/LoginPage.vue
  src/stores/loginInfo.js
Labels: ⏫프론트-개발

#27 Jh/contract list fix01
  package-lock.json
  package.json
  src/pages/board/BoardAddPage.vue
  src/pages/board/BoardModifyPage.vue
  src/pages/contract/ContractListPage.vue
Labels: ⏫프론트-개발, ✅테스트

#28 Jh/replyfront
  package-lock.json
  package.json
  src/layouts/Editor.vue
  src/main.js
  src/pages/board/BoardAddPage.vue
  src/pages/board/BoardDetailPage.vue
  src/pages/board/BoardListPage.vue
  src/pages/board/SuggestionBoardAddPage.vue
  src/pages/contract/ContractListPage.vue
  src/pages/login/LoginPage.vue
  src/stores/notificationStore.js
Labels: ⏫프론트-개발

#30 [save] 현재까지 작업 내용 커밋
  src/layouts/AppSidebar.vue
  src/pages/login/LoginPage.vue
  src/pages/sales/SalesRanking.vue
Labels: ⏫프론트-개발, ✅기타작업

#29 [fix] boarddetailfix
  package-lock.json
  src/pages/board/BoardDetailPage.vue
  src/pages/contract/ContractAddModifyPage.vue
  src/pages/contract/ContractListPage.vue
  src/pages/login/LoginPage.vue
  src/pages/login/PasswordFind.vue
Labels: ⏫프론트-개발, 🍀코드리뷰

#33 [fix]: 프론트앤드 코드 수정
  package-lock.json
  package.json
  src/main.js
  src/pages/board/BoardDetailPage.vue
  src/pages/board/BoardListPage.vue
  src/pages/board/BoardModifyPage.vue
  src/pages/contract/ContractAddModifyPage.vue
  src/stores/notificationStore.js
Labels: ⏫프론트-개발, 🍀코드리뷰

#35 HHJ/excel
  src/pages/salesMember/SalesMembersListPage.vue
  src/pages/team/TeamDetailPage.vue
Labels: ⏫프론트-개발, 🍀코드리뷰

#36 Jgn/excel
  index.html
  src/pages/contract/ContractListPage.vue
Labels: ⏫프론트-개발, 🍀코드리뷰

#34 Jh/password find fix
  src/pages/contract/ContractAddModifyPage.vue
  src/pages/login/PasswordFind.vue
Labels: ⏫프론트-개발, 🍀코드리뷰

#37 Jh/code fix01
  src/main.js
  src/stores/notificationStore.js
Labels: ⏫프론트-개발, 🍀코드리뷰

#39 Psj/merge
  src/pages/sales/SalesPersonal.vue
  src/pages/sales/charts/SalesPersonalTableChart.js
Labels: ⏫프론트-개발

#40 [fix]listcomponent수정
  src/layouts/ListComponent.vue
Labels: ⏫프론트-개발, 🍀코드리뷰

#41 [feat] login sidebar 작업
  src/layouts/AppSidebar.vue
  src/pages/login/LoginPage.vue
  src/stores/loginInfo.js
Labels: ⏫프론트-개발

#42 [hotfix] 긴급 수정 3
  src/main.js
  src/pages/login/LoginPage.vue
  src/pages/sales/SalesPersonal.vue
  src/pages/sales/SalesRanking.vue
  src/stores/loginInfo.js
Labels: ⏫프론트-개발

#43 HHJ/fix-address
  index.html
  src/layouts/AppSidebar.vue
  src/pages/salesMember/SalesMembersAddPage.vue
  src/pages/salesMember/SalesMembersDetailPage.vue
  src/pages/salesMember/SalesMembersModifyPage.vue
  src/router/routes.js
Labels: ⏫프론트-개발, 🍀코드리뷰, ✅기타작업

#44 HHJ/access
  src/layouts/AppSidebar.vue
  src/pages/login/LoginPage.vue
  src/router/index.js
  src/router/routes.js
Labels: ⏫프론트-개발, 🍀코드리뷰

#45 [fix]: 사이드 바 프로필 사진 위치 변경
  src/layouts/AppSidebar.vue
Labels: ⏫프론트-개발, ✅테스트, ✅기타작업

#46 Psj/mypage image
  src/pages/login/LoginPage.vue
  src/pages/main/HomePage.vue
  src/pages/mypage/MyPage.vue
Labels: ⏫프론트-개발

#50 [fix]: 게시판 수정 시 기존의 게시판 내용이 불러오지 않았던 현상, 답글완료표시가 새로고침을 누르면 삭제되는 현상 수정
  src/layouts/Editor.vue
  src/pages/board/BoardDetailPage.vue
  src/pages/board/BoardModifyPage.vue
Labels: ⏫프론트-개발

#52 [fix]: sidebar Alioth 로고 추가
  src/layouts/AppSidebar.vue
Labels: ⏫프론트-개발

#51 Hhj/salesMembers_filterNexcel
  public/postcode.v2.js
  src/layouts/AppSidebar.vue
  src/pages/contract/ContractListPage.vue
  src/pages/salesMember/SalesMembersDetailPage.vue
  src/pages/salesMember/SalesMembersListPage.vue
  src/pages/team/TeamDetailPage.vue
  src/pages/team/TeamListPage.vue
  src/router/routes.js
Labels: ⏫프론트-개발

#53 [fix]:quill 에디터 사진 업로드시 base64 -> s3 url로 표기 및 db저장 , 간단한 사진 크기 조 정 구현
  package-lock.json
  package.json
  src/layouts/Editor.vue
  src/pages/board/BoardAddPage.vue
Labels: ⏫프론트-개발

#54 [fix]: quill editor 코드수정
  src/layouts/AppSidebar.vue
  src/layouts/Editor.vue
  src/pages/board/BoardListPage.vue
  src/pages/contract/ContractAddModifyPage.vue
  src/pages/contract/ContractDetailPage.vue
  src/pages/contract/ContractListPage.vue
  src/pages/contract/ContractModifyPage.vue
Labels: ⏫프론트-개발, 🍀코드리뷰

#55 순위 탭 수정, 차트 버그 해결
  src/pages/main/HomePage.vue
  src/pages/main/charts/AnalyticsTransactions.vue
  src/pages/main/charts/AnalyticsTransactions_temp.vue
  src/pages/sales/SalesPage.vue
  src/pages/sales/SalesRanking.vue
  src/pages/sales/charts/AnalyticsUserTable.vue
  src/pages/sales/charts/SalesAnalytics.vue
  src/pages/sales/charts/SalesPageCountPieChart.js
  src/pages/sales/charts/SalesPagePieChart.js
  src/pages/sales/charts/SalesPageTarget.js
Labels: ⏫프론트-개발
