Repository GyeongNam/Alioth-Front, pull requests merged in 2024-05, with the labels that each got.

#58 [fix] 기존 UI 변경
  src/pages/sales/SalesPage.vue
  src/pages/sales/SalesPersonal.vue
  src/pages/sales/SalesRanking.vue
  src/pages/sales/charts/SalesAnalytics.vue
  src/pages/sales/charts/SalesPageTarget.js
Labels: ⏫프론트-개발

#59 Hhj/fix
  index.html
  public/Alioth.png
  src/layouts/AppSidebar.vue
  src/pages/mypage/ModalMyPage.vue
  src/pages/mypage/MyPage.vue
  src/pages/salesMember/SalesMembersAddPage.vue
  src/pages/salesMember/SalesMembersDetailPage.vue
  src/pages/team/TeamDetailPage.vue
  src/router/routes.js
Labels: ⏫프론트-개발, 🍀코드리뷰, 🙋‍♀️🙋‍♀️질문

#60 JGN/pr-error 에러수정
  package-lock.json
  package.json
  src/layouts/AppSidebar.vue
  src/pages/salesMember/SalesMembersDetailPage.vue
Labels: ✅기타작업

#61 Jgn/front deploy
  .github/workflows/S3deploy.yaml
  src/layouts/AppSidebar.vue
Labels: ⏫프론트-개발, 🛰데브옵스-개발

#64 Hhj/fix profile image
  src/pages/salesMember/SalesMembersDetailPage.vue
Labels: ⏫프론트-개발, 🍀코드리뷰, 🙋‍♀️🙋‍♀️질문

#65 Hhj/fix- salesMembersDetail_authentication
  src/pages/salesMember/SalesMembersDetailPage.vue
Labels: ⏫프론트-개발, 🍀코드리뷰

#66 Hhj/fix route
  src/layouts/AppSidebar.vue
  src/pages/mypage/ModalMyPage.vue
  src/pages/mypage/MyPage.vue
  src/pages/salesMember/SalesMembersDetailPage.vue
  src/router/routes.js
Labels: ⏫프론트-개발, 🍀코드리뷰

#68 HHJ/fix-clickBubbling
  src/pages/salesMember/SalesMembersDetailPage.vue
Labels: ⏫프론트-개발, ✅기타작업

#69 [fix]: front 디자인 변경
  src/pages/board/BoardDetailPage.vue
  src/pages/team/TeamDetailPage.vue
Labels: ⏫프론트-개발

#70 HHJ/사원추가 페이지 사진 미리보기 기능 추가
  src/pages/salesMember/SalesMembersAddPage.vue
Labels: ⏫프론트-개발, ✅기타작업

#71 [fix] sidebar code fix
  src/layouts/AppSidebar.vue
Labels: ⏫프론트-개발, 🍀코드리뷰

#72 순위 페이지에 보험 금액, 건수 파이차트 변경
  src/pages/sales/SalesPage.vue
  src/pages/sales/SalesPersonal.vue
  src/pages/sales/SalesRanking.vue
  src/pages/sales/SalesTeam.vue
  src/pages/sales/SalesTotal.vue
  src/pages/sales/charts/SalesPageCountPieChart.js
  src/pages/sales/charts/SalesPagePieChart.js
  src/stores/SalesRankingStore.js
Labels: ⏫프론트-개발

#73 Hhj/authorization
  package-lock.json
  package.json
  src/layouts/AppHeader.vue
  src/layouts/AppSidebar.vue
  src/pages/board/BoardListPage.vue
  src/pages/contract/ContractAddModifyPage.vue
  src/pages/contract/ContractListPage.vue
  src/pages/login/LoginPage.vue
  src/pages/main/HomePage.vue
  src/pages/salesMember/SalesMembersAddPage.vue
  src/pages/salesMember/SalesMembersDetailPage.vue
  src/pages/salesMember/SalesMembersListPage.vue
  src/pages/schedule/SchedulePage.vue
  src/pages/team/TeamAddPage.vue
  src/pages/team/TeamListPage.vue
  src/plugins/vuetify.js
  vite.config.mjs
Labels: ⏫프론트-개발, 🍀코드리뷰, ✅기타작업

#74 [fix]: 사이드바 매출 탭 수정
  src/layouts/AppSidebar.vue
  src/pages/board/BoardDetailPage.vue
  src/pages/board/BoardListPage.vue
  src/pages/board/BoardModifyPage.vue
  src/pages/board/SuggestionBoardAddPage.vue
  src/pages/contract/ContractAddModifyPage.vue
  src/pages/contract/ContractDetailPage.vue
  src/pages/contract/ContractListPage.vue
  src/pages/sales/SalesPage.vue
  src/pages/sales/SalesPersonal.vue
  src/pages/sales/SalesTeam.vue
  src/pages/salesMember/SalesMembersAddPage.vue
  src/pages/salesMember/SalesMembersDetailPage.vue
  src/pages/salesMember/SalesMembersListPage.vue
  src/pages/team/TeamDetailPage.vue
  src/pages/team/TeamListPage.vue
Labels: ⏫프론트-개발

#76 [feat] 매출 메인 페이지 작성
  src/pages/sales/SalesPage.vue
  src/pages/sales/SalesRanking.vue
  src/pages/sales/charts/SalesAnalytics.vue
  src/pages/sales/charts/SalesPageTarget.js
  src/stores/SalesStore.js
Labels: ⏫프론트-개발

#77 Jgn/search
  src/pages/team/TeamAddPage.vue
  src/pages/team/TeamDetailPage.vue
  src/pages/team/TeamListPage.vue
Labels: ⏫프론트-개발

#78 Hhj/team detail
  src/pages/salesMember/SalesMembersDetailPage.vue
  src/pages/team/TeamDetailPage.vue
Labels: ⏫프론트-개발

#79 Psj/dashboard 01
  src/pages/main/HomePage.vue
Labels: ⏫프론트-개발

#80 [feat] 매출 팀 작성
  src/pages/sales/SalesPage.vue
  src/pages/sales/SalesRanking.vue
  src/pages/sales/charts/SalesPageTeamTarget.js
  src/stores/SalesStore.js
Labels: ⏫프론트-개발

#81 [feat]: 계약 화면 수정
  src/pages/board/BoardDetailPage.vue
  src/pages/board/BoardListPage.vue
  src/pages/contract/ContractAddModifyPage.vue
  src/pages/contract/ContractCancelPage.vue
  src/pages/contract/ContractDetailPage.vue
  src/pages/contract/ContractModifyPage.vue
  src/pages/salesMember/SalesMembersListPage.vue
Labels: ⏫프론트-개발

#82 [feat]: 게시판 권한 설정 및 디자인 수정, 마이페이지 본인 외 프로필 이미지 변경 불가 권한 설정
  src/pages/board/BoardDetailPage.vue
  src/pages/board/BoardListPage.vue
  src/pages/board/BoardModifyPage.vue
  src/pages/salesMember/SalesMembersDetailPage.vue
Labels: ⏫프론트-개발

#84 [feat]: 게시글 조회, 사원상세정보페이지 디자인 수정
  src/pages/board/BoardDetailPage.vue
  src/pages/board/BoardListPage.vue
  src/pages/board/BoardModifyPage.vue
  src/pages/salesMember/SalesMembersDetailPage.vue
Labels: ⏫프론트-개발

#83 Psj/sales hq 01 -매출 전사 -> 팀 매출 리스트
  src/pages/main/HomePage.vue
  src/pages/sales/SalesPage.vue
  src/stores/SalesStore.js
Labels: ⏫프론트-개발

#86 [feat]: 사원 자기 정보 수정 오류 수정
  src/pages/board/BoardAddPage.vue
  src/pages/board/SuggestionBoardDetailPage.vue
  src/pages/sales/SalesPage.vue
  src/pages/salesMember/SalesMembersDetailPage.vue
Labels: ⏫프론트-개발

#87 Psj/sales fix 01
  src/pages/main/HomePage.vue
  src/pages/sales/SalesPage.vue
Labels: ⏫프론트-개발

#88 [fix] 매출 페이지 오타 제거
  src/pages/sales/SalesPage.vue
Labels: ⏫프론트-개발

#90 [fix] 프론트 요청 url 수정
  src/pages/sales/SalesPage.vue
  src/pages/sales/charts/SalesPageCountPieChart.js
  src/pages/sales/charts/SalesPagePieChart.js
  src/pages/sales/charts/SalesPageTarget.js
  src/pages/sales/charts/SalesPageTeamTarget.js
Labels: ⏫프론트-개발
